-- PROJETO DA DISPLINA DE GDI 
-- ALUNOS: LUCAS FERROPADILHA PAIVA
--         LÍGIA FERROPADILHA PAIVA <- minha esposa
--         MARIANA MELO
--         NATHÁLIA COELHO
--         THIAGO 
--         JULIA DIAS
---------------------------------------------------------------------------------------
-- SISTEMA DE EMISSÃO DE CNH
---------------------------------------------------------------------------------------

-- TABELA INSTRUTOR
CREATE TABLE Instrutor (
CPF VARCHAR(4) PRIMARY KEY, 
nome VARCHAR(50), 
salario NUMBER(5)
);

-- TABELA DETRAN
CREATE TABLE Detran (
COD VARCHAR(4) PRIMARY KEY,
endereço_logradouro VARCHAR(50),
endereço_CEP VARCHAR(8)
);

-- TABELA AUTO-ESCOLA
CREATE TABLE AutoEscola (
CNPJ VARCHAR(14),
COD VARCHAR(4),
CPF VARCHAR(11) NOT NULL,
nome VARCHAR(50),
CONSTRAINT FK_AUTOESCOLA_DETRAN FOREIGN KEY (COD) REFERENCES Detran (COD),
CONSTRAINT FK_AUTOESCOLA_INSTRUTOR FOREIGN KEY (CPF) REFERENCES instrutor (CPF),
CONSTRAINT PK_AUTOESCOLA PRIMARY KEY(CNPJ,COD)
);

--TABELA CONTATOS
CREATE TABLE Contatos (
CNPJ VARCHAR (14),
COD VARCHAR (4),
contato VARCHAR(8),
CONSTRAINT PK_CONTATOS_AUTOESCOLA PRIMARY KEY (CNPJ, COD, contato),
CONSTRAINT FK_CONTATOS_AUTOESCOLA FOREIGN KEY (CNPJ, COD) REFERENCES AutoEscola (CNPJ, COD)
);

-- TABELA ALUNO 
CREATE TABLE Aluno (
CPF VARCHAR (8) PRIMARY KEY, 
nome VARCHAR (50)
);

-- TABELA DA AULA
CREATE TABLE Da_aula (
CPF_aluno VARCHAR (8), 
CPF_instrutor VARCHAR (8),
CONSTRAINT PK_DA_AULA PRIMARY KEY (CPF_aluno, CPF_instrutor),
CONSTRAINT FK_DA_AULA_ALUNO FOREIGN KEY (CPF_aluno) REFERENCES Aluno (CPF),
CONSTRAINT FK_DA_AULA_INSTRUTOR FOREIGN KEY (CPF_instrutor) REFERENCES Instrutor (CPF),
);

-- TABELA TRABALHA
CREATE TABLE Trabalha (
CPF_instrutor VARCHAR (8),
CNPJ VARCHAR (14),
COD VARCHAR (4),
CONSTRAINT PK_TRABALHA PRIMARY KEY (CPF_instrutor, CNPJ, COD),
CONSTRAINT FK_TRABALHA_INSTRUTOR FOREIGN KEY (CPF_instrutor) REFERENCES Instrutor (CPF),
CONSTRAINT FK_TRABALHA_AUTOESCOLA FOREIGN KEY (CNPJ, COD) REFERENCES AutoEscola (CNPJ, COD),
);

-- TABELA MATRÍCULA
CREATE TABLE Matricula (
COD_auto_escola VARCHAR (4),
CNPJ VARCHAR (14),
CPF VARCHAR (8) NOT NULL,
COD_detran VARCHAR (4),
DATA_DE_INICIO DATE UNIQUE NOT NULL,
CONSTRAINT PK_MATRICULA PRIMARY KEY (COD_auto_escola, CNPJ),
CONSTRAINT FK_MATRICULA_AUTOESCOLA FOREIGN KEY (COD_auto_escola, CNPJ) REFERENCES AutoEscola (COD_auto_escola, CNPJ),
CONSTRAINT FK_MATRICULA_DETRAN FOREIGN KEY (COD_detran) REFERENCES Detran (COD),
CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (CPF) REFERENCES Aluno (CPF),
);

-- TABELA FUNCIONÁRIO
CREATE TABLE Funcionario (
CPF VARCHAR (8) PRIMARY KEY,
COD VARCHAR (4),
Chefe VARCHAR (8), 
CONSTRAINT FK_FUNCIONARIO_DETRAN FOREIGN KEY (COD) REFERENCES Detran (COD),
CONSTRAINT FK_FUNCIONARIO_FUNCIONARIO FOREIGN KEY (Chefe) REFERENCES Funcionario (CPF)
);

-- TABELA EXAME 
CREATE TABLE Exame (
COD VARCHAR (4) PRIMARY KEY,
tipo VARCHAR (20) 
);

-- TABELA REALZA 
CREATE TABLE Realiza (
COD VARCHAR (4),
CPF_funcionario VARCHAR (8) NOT NULL,
CPF_aluno VARCHAR (8),
CONSTRAINT PK_REALIZA PRIMARY KEY (COD, CPF_aluno),
CONSTRAINT FK_REALIZA_EXAME FOREIGN KEY (COD) REFERENCES Exame (COD),
CONSTRAINT FK_REALIZA_FUNCIONARIO FOREIGN KEY (CPF_funcionario) REFERENCES Funcionario (CPF),
CONSTRAINT FK_REALIZA_ALUNO FOREIGN KEY (CPF_aluno) REFERENCES Aluno (CPF)
);

